/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment2;

import javax.swing.JOptionPane;

/**
 *
 * @author k00223375
 */
public class TestClass extends javax.swing.JFrame {

    public LinkedQueue empQueue;
    public Employee emp1;
    public Employee emp2;
    /**
     * Creates new form Main
     */
    public TestClass() {
        initComponents();
        //setJTA();
        empQueue=new LinkedQueue();
        emp1 = new Employee();
        emp2 = new Employee(987,"Rain","Carl",33);
        
        empQueue.append(emp1);
        empQueue.append(emp2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        insertButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        qSizeButton = new javax.swing.JButton();
        frontButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        printQueue = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        qSizeButton.setText("Queue Size");
        qSizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qSizeButtonActionPerformed(evt);
            }
        });

        frontButton.setText("Front");
        frontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontButtonActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        printQueue.setText("Print Queue");
        printQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printQueueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qSizeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frontButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printQueue)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton)
                    .addComponent(deleteButton)
                    .addComponent(searchButton)
                    .addComponent(qSizeButton)
                    .addComponent(frontButton)
                    .addComponent(printQueue))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (empQueue.size() <= 0) {
            jTextField1.setText("Queue is empty! No DELETE has occurred!");
            
        } else {
            empQueue.serve();
            jTextField1.setText("DELETE has occurred!");
            setJTA();
            jTextArea.append(empQueue.printQueue());
            jTextArea.append("-------------------------------------------------------------------------- \n");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if (empQueue.size() == 0) {
            jTextField1.setText("Queue is empty! \n");
            

        } else {
            String input = JOptionPane.showInputDialog("Search for Employee by Lastname: ");
            String lName = input.toUpperCase();
            if(empQueue.searchQueue(lName)==true)
            {
                jTextField1.setText(lName+ ", is in the Queue! \n");
            }
            else
            {
                jTextField1.setText(lName + ", not found in the Queue! \n");
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void qSizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qSizeButtonActionPerformed
        // TODO add your handling code here:
        String outputText="Size of the Queue is "+ empQueue.size();
        jTextField1.setText(outputText);
    }//GEN-LAST:event_qSizeButtonActionPerformed

    private void frontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontButtonActionPerformed
        // TODO add your handling code here:
        
        if (empQueue.size() <= 0) {
            jTextField1.setText("Queue is empty! No Employee Details to Print!");
            
        } else {
           
            jTextArea.append("The Front of the Queue is: \n");
            jTextArea.append("Emp No.\tSurname\tFirstname\tAge\n");
            jTextArea.append(empQueue.front()+"\n");
            jTextArea.append("-------------------------------------------------------------------------- \n");

        }
        
    }//GEN-LAST:event_frontButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void printQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printQueueActionPerformed
        // TODO add your handling code here:
        if (empQueue.size() <= 0) {
            jTextField1.setText("Queue is empty! No Employee Details to Print!");
            
        } else {
           
            setJTA();
            jTextArea.append(empQueue.printQueue());
            jTextArea.append("-------------------------------------------------------------------------- \n");

        }
    }//GEN-LAST:event_printQueueActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Input Employee Number: ");
        int idNum = Integer.parseInt(input);

        input = JOptionPane.showInputDialog("Input Last Name: ");
        String lName = input.toUpperCase();
        
        input = JOptionPane.showInputDialog("Input First Name: ");
        String fName = input;

        input = JOptionPane.showInputDialog("Input Age: ");
        int age = Integer.parseInt(input);


        emp1 = new Employee(idNum, lName,fName, age);
        empQueue.append(emp1);
        jTextField1.setText("New Employee Details have been added to the End of the Queue!");
        setJTA();
        jTextArea.append(empQueue.printQueue());
        jTextArea.append("-------------------------------------------------------------------------- \n");
        
    }//GEN-LAST:event_insertButtonActionPerformed

    public void setJTA()
    {
        jTextArea.append("The Queue Contains: \n");
        jTextArea.append("Emp No.\tSurname\tFirstname\tAge\n");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton frontButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton printQueue;
    private javax.swing.JButton qSizeButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
